CodeTechnologiesMVCADO/Controllers/PrometricCandidateController.cs
using CodeTechnologiesMVCADO.CodeTechWCF;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;

namespace CodeTechnologiesMVCADO.Controllers
{
    public class PrometricCandidateController : Controller
    {
        CodeTechnologiesServicesClient proxy = new CodeTechnologiesServicesClient();
        // GET: /PrometricCandidate/

        public ActionResult Index()
        {
            var pclist = proxy.GetAllPrometricCandidates();
            return View(pclist);
        }

        public ActionResult Create()
        {
            var examNatures = proxy.GetAllExamNature();
            IList<SelectListItem> enatureitems = new List<SelectListItem>();
            foreach (ExamNature nature in examNatures)
            {
                enatureitems.Add(new SelectListItem { Text = nature.Name, Value = nature.Id.ToString() });
            }
            ViewBag.examNatureDD = enatureitems;
            return View();
        }

        public ActionResult BulkUpload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BulkUpload(HttpPostedFileBase file)
        {
            if (Request.Files["FileUpload"].ContentLength > 0)
            {
                int filePosition = 0;
                int filePart = 16 * 1024;
                byte[] bufferData = new byte[filePart];
                Stream fileStream = Request.Files["FileUpload"].InputStream;
                try
                {
                    long actualFileSize = Request.Files["FileUpload"].ContentLength;
                    fileStream.Position = filePosition;
                    int fileBytesRead = 0;
                    while (filePosition != actualFileSize)
                    {
                        fileBytesRead = fileStream.Read(bufferData, 0, filePart);
                        if (fileBytesRead != bufferData.Length)
                        {
                            filePart = fileBytesRead;
                            byte[] bufferedDataToWrite = new byte[fileBytesRead];
                            Array.Copy(bufferData, bufferedDataToWrite, fileBytesRead);
                            bufferData = bufferedDataToWrite;
                        }

                        proxy.BulkUploadPrometricCandidates(new FileData
                        {
                            FileName = Request.Files["FileUpload"].FileName,
                            BufferData = bufferData,
                            FilePosition = filePosition
                        });
                        filePosition += fileBytesRead;


                    }

                }
                catch (FaultException fex)
                {
                    return null;
                }
                finally
                {
                    fileStream.Close();
                }
                
            }
            return RedirectToAction("Index");

        }

    }
}

CodeTechnologiesMVCADO/Views/PrometricCandidate/BulkUpload.cshtml
@{
    ViewBag.Title = "BulkUpload";
}

<h2>Bulk Candidate's Upload</h2>

@using (Html.BeginForm("BulkUpload", "PrometricCandidate", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div>
          <input type="file" id="FileUpload"                    
                            name="FileUpload" required data-val="true" data-val-required="please select a file"/>
            
          <input type="submit" id="Submit" class="submit" value="Upload"  title="Click to upload file"/> 
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CodeTechnologiesMVCADO/Views/PrometricCandidate/Create.cshtml
@model CodeTechnologiesMVCADO.CodeTechWCF.PrometricCandidate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>PrometricCandidate</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExamNature)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.ExamNature, ViewBag.examNatureDD as List<SelectListItem>)
            @Html.ValidationMessageFor(model => model.ExamNature)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExamId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ExamId)
            @Html.ValidationMessageFor(model => model.ExamId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.VoucherId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.VoucherId)
            @Html.ValidationMessageFor(model => model.VoucherId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CandidateId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CandidateId)
            @Html.ValidationMessageFor(model => model.CandidateId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExamStatus)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ExamStatus)
            @Html.ValidationMessageFor(model => model.ExamStatus)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Attempts)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Attempts)
            @Html.ValidationMessageFor(model => model.Attempts)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExamDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ExamDate)
            @Html.ValidationMessageFor(model => model.ExamDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EmailAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EmailAddress)
            @Html.ValidationMessageFor(model => model.EmailAddress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.InstituteId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.InstituteId)
            @Html.ValidationMessageFor(model => model.InstituteId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ClientId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ClientId)
            @Html.ValidationMessageFor(model => model.ClientId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Abroad)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Abroad)
            @Html.ValidationMessageFor(model => model.Abroad)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SiteId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SiteId)
            @Html.ValidationMessageFor(model => model.SiteId)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CodeTechnologiesMVCADO/Views/PrometricCandidate/Delete.cshtml
@model CodeTechnologiesMVCADO.CodeTechWCF.PrometricCandidate

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>PrometricCandidate</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ExamNature)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExamNature)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ExamId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExamId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.VoucherId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.VoucherId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CandidateId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CandidateId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ExamStatus)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExamStatus)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Attempts)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Attempts)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ExamDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExamDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EmailAddress)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EmailAddress)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.InstituteId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.InstituteId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ClientId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ClientId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Abroad)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Abroad)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SiteId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SiteId)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

CodeTechnologiesMVCADO/Views/PrometricCandidate/Details.cshtml
@model CodeTechnologiesMVCADO.CodeTechWCF.PrometricCandidate

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>PrometricCandidate</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ExamNature)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExamNature)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ExamId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExamId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.VoucherId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.VoucherId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CandidateId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CandidateId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ExamStatus)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExamStatus)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Attempts)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Attempts)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ExamDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ExamDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EmailAddress)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EmailAddress)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.InstituteId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.InstituteId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ClientId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ClientId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Abroad)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Abroad)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SiteId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SiteId)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CodeTechnologiesMVCADO/Views/PrometricCandidate/Edit.cshtml
@model CodeTechnologiesMVCADO.CodeTechWCF.PrometricCandidate

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>PrometricCandidate</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExamNature)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ExamNature)
            @Html.ValidationMessageFor(model => model.ExamNature)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExamId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ExamId)
            @Html.ValidationMessageFor(model => model.ExamId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.VoucherId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.VoucherId)
            @Html.ValidationMessageFor(model => model.VoucherId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CandidateId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CandidateId)
            @Html.ValidationMessageFor(model => model.CandidateId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExamStatus)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ExamStatus)
            @Html.ValidationMessageFor(model => model.ExamStatus)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Attempts)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Attempts)
            @Html.ValidationMessageFor(model => model.Attempts)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ExamDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ExamDate)
            @Html.ValidationMessageFor(model => model.ExamDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EmailAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EmailAddress)
            @Html.ValidationMessageFor(model => model.EmailAddress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.InstituteId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.InstituteId)
            @Html.ValidationMessageFor(model => model.InstituteId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ClientId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ClientId)
            @Html.ValidationMessageFor(model => model.ClientId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Abroad)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Abroad)
            @Html.ValidationMessageFor(model => model.Abroad)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SiteId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SiteId)
            @Html.ValidationMessageFor(model => model.SiteId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CodeTechnologiesMVCADO/Views/PrometricCandidate/Index.cshtml
@model IEnumerable<CodeTechnologiesMVCADO.CodeTechWCF.PrometricCandidate>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")

    @Html.ActionLink("Bulk Upload", "BulkUpload")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExamNature)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExamId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VoucherId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CandidateId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExamStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Attempts)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExamDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InstituteId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Abroad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SiteId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExamNature)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExamId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VoucherId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CandidateId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExamStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Attempts)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExamDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InstituteId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClientId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Abroad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SiteId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>